name: Feature Request
description: Suggest a new feature or enhancement for the Fronius Homey App
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What kind of feature are you requesting?
      options:
        - New Driver (new equipment support)
        - Enhancement to existing driver
        - New capability/measurement
        - UI/UX improvement
        - Integration with other apps
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: What problem would this feature solve? What's your use case?
      placeholder: Describe the problem or use case...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
    validations:
      required: false

  - type: dropdown
    id: equipment
    attributes:
      label: Related Fronius Equipment
      description: Which Fronius equipment is this related to?
      multiple: true
      options:
        - Inverter
        - Smartmeter
        - Ohmpilot
        - Storage
        - PowerFlow
        - DataManager
        - Other / Not equipment-specific
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information, screenshots, or examples that might help
    validations:
      required: false
